config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  root 'pages#index'
  resources :trainings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :training
  validates_presence_of :name
  validates_presence_of :reps
  validates_numericality_of :reps, greater_than_or_equal_to: 0  
  validates_numericality_of :weight, greater_than_or_equal_to: 0 
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user 
  has_many :exercises, inverse_of: :training, dependent: :destroy
  accepts_nested_attributes_for :exercises

  validates_presence_of :date
  validates_date :date, :between => [Date.today.prev_year(10), Date.today.next_year(10)]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trainings, dependent: :destroy
  attr_accessor :login
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]

  validates :username, presence: true, 
            uniqueness: { case_sensitive: false },
            length: { minimum: 3 }, 
            format: { with: /\A[a-zA-Z0-9_]+\z/, message: "only allows letters, numbers and '_'" }

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
 
    def configure_permitted_parameters
      added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
    @training.exercises.build
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = current_user.trainings.build(training_params)
    #@training.exercises.build

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:date, exercises_attributes: [:id, :name, :description, :reps, :weight, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "info"
    when :error then "error"
    when :alert then "warning"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/layouts/_navigation.html.haml
%nav.navbar-dark.bg-dark
  .container
    .row
      .nav-item= link_to "Home",   root_path, :class => "nav-link"

      -if current_user.blank?
        = render 'layouts/navigation/no_logged_user'
      -else
        = render 'layouts/navigation/logged_user'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WorkoutTracker
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navigation'
    .container
      - flash.each do |key, value|
        %div{class: "#{flash_class(key)}"}
          = value
      = yield

app/views/layouts/navigation/_logged_user.html.haml
.nav-item= link_to 'Edit Profile', edit_user_registration_path, :class => "nav-link"
.nav-item= link_to 'Add training', new_training_path, :class => "nav-link"
.nav-item= link_to 'Your trainings', trainings_path, :class => "nav-link"
.nav-item= link_to 'Log out', destroy_user_session_path, method: :delete, :class => "nav-link"

app/views/layouts/navigation/_no_logged_user.html.haml
.nav-item= link_to 'Login', login_path, :class => "nav-link"
.nav-item= link_to 'Signup', signup_path, :class => "nav-link"

app/views/pages/index.html.haml
%h1 Welcome! 
-if current_user
  = render 'trainings/index_logged_user'

app/views/trainings/_exercise_fields.html.haml
.nested-fields
  =f.input :name, placeholder: "name of exercise"
  =f.input :description, placeholder: "Write something more about this exercise."
  =f.input :reps
  =f.input :weight
  .col-sm-4.offset-sm-4
    = link_to_remove_association "remove exercise", f,
                                  class: [ 'btn-danger', 'button-log', 'link-to-as-button' ]

app/views/trainings/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@training) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :date, start_year: Date.today.year - 10,
                    end_year: Date.today.year + 10,
                    use_short_month: true,
                    order: [:day, :month, :year]
    %h3 Exercises
    = f.simple_fields_for :exercises do |exercise|
      = render 'exercise_fields', f: exercise
    .col-sm-4.offset-sm-4
      = link_to_add_association 'add exercise', f, :exercises,
                                class: [ 'btn-primary', 'button-log', 'link-to-as-button' ]
  .form-actions
    = f.button :submit, class: [ 'btn-success',
                                 'btn-block' ]

app/views/trainings/_index_logged_user.html.haml
%h1 Listing trainings
%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - current_user.trainings.each do |training|
      %tr
        %td= training.date
        %td= link_to 'Show', training
        %td= link_to 'Edit', edit_training_path(training)
        %td= link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Training', new_training_path 

app/views/trainings/edit.html.haml
%h1 Editing training

= render 'form'

= link_to 'Show', @training
\|
= link_to 'Back', trainings_path

app/views/trainings/index.html.haml
-if current_user
  = render 'trainings/index_logged_user'

app/views/trainings/new.html.haml
%h1 Add new training

= render 'form'

= link_to 'Back', trainings_path

app/views/trainings/show.html.haml
%p#notice= notice
%h3 
  Date of Training:
  = @training.date
- @training.exercises.each do |ex|
  %ul
    %li
      %button.btn.btn-lg.btn-info{"data-content" => ex.description,
                                  "data-toggle" => "popover",
                                  "title" => "Description",
                                  "type" => "button"}
        = ex.name
    %li= "Reps: #{ex.reps}"
    %li= "Weight: #{ex.weight}"

= link_to 'Edit', edit_training_path(@training)
\|
= link_to 'Back', trainings_path